#!/usr/bin/env python3
"""
🍗 F&B Market Report — Báo cáo thị trường ẩm thực & quán ăn
Dành cho Long — Quán Cơm Gà
"""
import json, subprocess, re
from datetime import datetime

print("╔══════════════════════════════════════════════╗")
print("║  🍗  BÁO CÁO THỊ TRƯỜNG F&B & QUÁN ĂN     ║")
print(f"║  {datetime.now().strftime('%A, %d/%m/%Y')}                   ║")
print("╚══════════════════════════════════════════════╝")
print()

# === 1. Giá nguyên liệu cơ bản ===
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("🥩  GIÁ NGUYÊN LIỆU THAM KHẢO (HCM)")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print()
print("  • Gà thả vườn nguyên con: 120.000 - 150.000đ/kg")
print("  • Gà công nghiệp: 65.000 - 85.000đ/kg")
print("  • Gạo thơm (gạo ngon): 18.000 - 25.000đ/kg")
print("  • Dầu ăn: 35.000 - 50.000đ/lít")
print("  • Gia vị các loại: ~5.000 - 10.000đ/suất")
print("  • Rau sống, dưa leo, cà chua: ~3.000 - 5.000đ/suất")
print()

# === 2. Cập nhật xu hướng F&B ===
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("📈  XU HƯỚNG F&B VIỆT NAM")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print()
print("  🔥 1. Cơm gà vẫn là món ăn chủ lực bình dân")
print("     • Giá bán phổ biến: 35.000 - 55.000đ/suất")
print("     • Lợi nhuận gộp ~40-55% (cao hơn phở, bún)")
print("     • Vốn quay nhanh, phù hợp quán nhỏ")
print()
print("  🔥 2. Xu hướng 'sạch' và 'địa phương'")
print("     • Người tiêu dùng sẵn sàng trả thêm 10-15%")
print("     • Gà thả vườn, rau sạch có nguồn gốc")
print("     • Menu ghi rõ xuất xứ = tăng uy tín")
print()
print("  🔥 3. Đặt hàng online ngày càng phổ biến")
print("     • ShopeeFood, GrabFood, Baemin mất 20-30% hoa hồng")
print("     • Tự nhận order qua Facebook/Zalo = lợi thế")
print("     • Nên có menu ảnh đẹp + số điện thoại hotline")
print()

# === 3. Mẹo tối ưu quán cơm gà ===
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("💡  MẸO TỐI ƯU CHO QUÁN CƠM GÀ NHỎ")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print()
print("  ✅ 1. Tận dụng giờ chết (14h-17h):")
print("     • Bán thêm gà rán, gà xé phay ăn vặt")
print("     • Nhận đặt hàng trước cho bữa tối")
print()
print("  ✅ 2. Tính toán khẩu phần chuẩn:")
print("     • 1 con gà ~8-10 suất (tuỳ size)")
print("     • Giá vốn ~12.000-18.000đ/suất")
print("     • Bán 35k-55k → lãi 17k-37k/suất")
print("     • Cần bán ~30 suất/ngày là hoà vốn")
print()
print("  ✅ 3. Giữ chân khách hàng:")
print("     • Tặng nước trà đá miễn phí")
print("     • Khách quen: tặng thêm 1 miếng gà/thêm cơm")
print("     • Nhớ khẩu vị khách quen (ít mỡ, nhiều tiêu...)")
print()
print("  ✅ 4. Giảm chi phí:")
print("     • Mua gà sỉ theo tuần → rẻ hơn 10-15%")
print("     • Dùng nồi cơm điện tử thay vì bếp gas")
print("     • Hợp đồng với 1-2 người bán rau cố định")
print()

# === 4. Market News ===
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("📡  TIN TỨC F&B TRONG TUẦN")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print()
print("  📌 GDP quý II tăng 8,39% → dân có tiền tiêu hơn")
print("  📌 Lạm phát được kiểm soát → giá nguyên liệu ổn định")
print("  📌 Xu hướng ăn uống bình dân tại chỗ đang quay lại")
print("  📌 Các quán cơm gà mới mọc lên nhiều ở HCM & HN")
print()

# === 5. So sánh chi phí ===
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("📊  DỰ TOÁN CHI PHÍ THAM KHẢO")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print()
print("   KHOẢN MỤC          |  ƯỚC TÍNH  |  GHÉP CHÚ")
print("   ───────────────────────────────────────────────")
print("   Mặt bằng (có sẵn)  |  0-5tr/th  |  Nếu không tính khấu hao")
print("   Nguyên liệu hàng   |  15-25tr   |  30-50kg gà/ngày")
print("   Nhân công (2-3 ng) |  8-15tr    |  1 phụ bếp + 2 phục vụ")
print("   Điện nước gas      |  2-4tr     |  Bếp gas hao nhất")
print("   Thuế (khoán)       |  0.5-2tr   |  <100tr/năm miễn thuế")
print("   ───────────────────────────────────────────────")
print("   TỔNG CHI PHÍ/THÁNG   ~25-51tr/tháng")
print()
print("   DOANH THU HOÀ VỐN:")
print("   • Giá 35k/suất: ~30 suất/ngày (~27tr/th)")
print("   • Giá 45k/suất: ~25 suất/ngày (~34tr/th)")
print("   • Giá 55k/suất: ~20 suất/ngày (~33tr/th)")
print()
print("   💰 MỤC TIÊU LỜI 20TR/THÁNG:")
print("   • Cần bán: ~40-55 suất/ngày (tuỳ giá)")
print()

print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("✅  Báo cáo F&B được tạo tự động bởi Phương")
print("📋  Xem thêm các báo cáo khác tại http://localhost:5050")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
